/**
 * iNES / NES 2.0 ROM parsing and CHR patching — pure functions, no DOM.
 */

export type RomKind = 'ines' | 'nes2' | 'raw';

export interface RomInfo {
  kind: RomKind;
  /** PRG-ROM size in bytes (0 for raw .chr files). */
  prgSize: number;
  /** Byte offset of CHR data within the file. */
  chrOffset: number;
  /** CHR data size in bytes. */
  chrSize: number;
  hasTrainer: boolean;
}

export class RomError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'RomError';
  }
}

const MAGIC = [0x4e, 0x45, 0x53, 0x1a]; // "NES\x1a"
const HEADER_SIZE = 16;
const TRAINER_SIZE = 512;
const PRG_UNIT = 16384;
const CHR_UNIT = 8192;

/** True if the buffer starts with the iNES magic bytes. */
export function hasInesMagic(data: Uint8Array): boolean {
  return data.length >= 4 && MAGIC.every((b, i) => data[i] === b);
}

/**
 * NES 2.0 size fields are 12 bits: the header's LSB byte plus a 4-bit
 * nibble extension. When the top nibble of the 12-bit value is 0xF the
 * field switches to exponent-multiplier form:
 * size = 2^exponent × (multiplier × 2 + 1), packed into the LSB byte
 * as EEEEEEMM.
 */
function nes2Size(lsb: number, nibble: number, unit: number): number {
  const units = (nibble << 8) | lsb;
  if (nibble === 0x0f) {
    const exponent = (lsb >> 2) & 0x3f;
    const multiplier = lsb & 0x03;
    return 2 ** exponent * (multiplier * 2 + 1);
  }
  return units * unit;
}

/**
 * Parse a .nes ROM header, or fall back to treating the buffer as a raw
 * CHR dump when the magic is absent and the length is a multiple of 16.
 * Throws RomError for CHR-RAM games and malformed files.
 */
export function parseRom(data: Uint8Array): RomInfo {
  if (hasInesMagic(data)) {
    if (data.length < HEADER_SIZE) {
      throw new RomError('File has the NES magic but is shorter than the 16-byte header.');
    }
    const isNes2 = (data[7] & 0x0c) === 0x08;
    let prgSize: number;
    let chrSize: number;
    if (isNes2) {
      prgSize = nes2Size(data[4], data[9] & 0x0f, PRG_UNIT);
      chrSize = nes2Size(data[5], (data[9] & 0xf0) >> 4, CHR_UNIT);
    } else {
      prgSize = data[4] * PRG_UNIT;
      chrSize = data[5] * CHR_UNIT;
    }
    const hasTrainer = (data[6] & 0x04) !== 0;
    const chrOffset = HEADER_SIZE + (hasTrainer ? TRAINER_SIZE : 0) + prgSize;
    if (chrSize === 0) {
      throw new RomError(
        'This game uses CHR-RAM: its graphics are generated by program code at runtime, ' +
          'so there is no CHR-ROM section to edit.',
      );
    }
    if (chrOffset + chrSize > data.length) {
      throw new RomError(
        `Header claims ${chrSize} bytes of CHR at offset ${chrOffset}, ` +
          `but the file is only ${data.length} bytes long.`,
      );
    }
    return { kind: isNes2 ? 'nes2' : 'ines', prgSize, chrOffset, chrSize, hasTrainer };
  }

  // Raw .chr fallback: bare tile data, 16 bytes per tile.
  if (data.length > 0 && data.length % 16 === 0) {
    return { kind: 'raw', prgSize: 0, chrOffset: 0, chrSize: data.length, hasTrainer: false };
  }

  throw new RomError(
    'Not an iNES/NES 2.0 ROM, and not a raw CHR dump (length must be a multiple of 16 bytes).',
  );
}

/** Copy the CHR section out of the file. */
export function extractChr(data: Uint8Array, info: RomInfo): Uint8Array {
  return data.slice(info.chrOffset, info.chrOffset + info.chrSize);
}

/**
 * Produce a patched copy of the original file with `chr` spliced back at
 * the CHR offset. Header, trainer, and PRG bytes are untouched.
 */
export function patchRom(original: Uint8Array, info: RomInfo, chr: Uint8Array): Uint8Array {
  if (chr.length !== info.chrSize) {
    throw new RomError(
      `CHR buffer is ${chr.length} bytes but the ROM's CHR section is ${info.chrSize} bytes.`,
    );
  }
  const out = original.slice();
  out.set(chr, info.chrOffset);
  return out;
}
